# Generated by Django 3.2.3 on 2021-10-17 03:09

import collections
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('productdataapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRegistration',
            fields=[
                ('id_bill', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('products', jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
                ('total_price', models.CharField(max_length=20)),
            ],
        ),
    ]
