# Generated by Django 3.2.3 on 2021-10-17 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productdataapi', '0002_billregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billregistration',
            name='id_bill',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
